test precommit controller

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,7 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npm run lint && npm run format:fix && git add -A .
+npm run lint && npm run format:fix && git add -A . || {
+  echo "Linting failed, please fix the errors and try again."
+  exit 1
+}
